# Generated by Django 5.1.1 on 2024-09-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
    ]
